// Package fft is a pure-Go (cgo-free) fast Fourier transform library — the
// numpy.fft / scipy.fft equivalent for Go.
//
// It computes the discrete Fourier transform (DFT) of complex and real signals
// of any length, with no dependency on the native FFTW3 C library. Power-of-two
// lengths use an iterative radix-2 Cooley–Tukey algorithm with a bit-reversal
// permutation; all other lengths are handled by Bluestein's chirp-z algorithm,
// so any length transforms correctly.
//
// The forward transform follows the unnormalized convention
//
//	X[k] = sum_{n=0}^{N-1} x[n] * exp(-2πi·k·n/N)
//
// and the inverse divides by N, so IFFT(FFT(x)) ≈ x to floating-point
// tolerance.
//
// Phase 0 is implemented: FFT, IFFT and FFTReal over arbitrary lengths. The
// butterfly loops live in an internal kernels package (scalar pure-Go now) so
// that SIMD kernels generated by go-asmgen across the six 64-bit Go targets
// (amd64, arm64, riscv64, loong64, ppc64le, s390x) can drop in later without
// changing the public API. See docs/plan-fft.md for the full roadmap.
package fft
