// Package fft is a pure-Go (cgo-free) fast Fourier transform library — the
// numpy.fft / scipy.fft equivalent for Go.
//
// It computes the discrete Fourier transform (DFT) of complex and real signals
// of any length, with no dependency on the native FFTW3 C library. A power-of-two
// length uses a split-radix kernel (≈⅓ fewer real multiplies than radix-4);
// other lengths whose prime factors are all small use mixed-radix Cooley–Tukey
// (radix-2/3/4/5 straight-line butterflies plus a general radix-p butterfly for
// the small primes 7/11/13); a prime length uses Rader's algorithm (above a size
// threshold) or Bluestein's chirp-z algorithm, so any length transforms
// correctly and fast. Twiddle factors are precomputed and cached per length
// (see Plan / NewPlan), so repeated transforms of one length recompute no
// sin/cos.
//
// The multi-dimensional transforms (FFT2/FFTN and their real and inverse forms)
// are separable: they apply a 1-D transform along each axis, and the
// independent lines of a large axis run in parallel across goroutines — a
// multicore path single-threaded references such as pocketfft cannot take. See
// docs/perf.md for the head-to-head benchmarks.
//
// The forward transform follows the unnormalized convention
//
//	X[k] = sum_{n=0}^{N-1} x[n] * exp(-2πi·k·n/N)
//
// and the inverse divides by N, so IFFT(FFT(x)) ≈ x to floating-point
// tolerance.
//
// Implemented so far: FFT, IFFT and FFTReal over arbitrary lengths (Phase 0),
// plus the real-optimized RFFT and IRFFT (Phase 1). RFFT returns only the
// non-redundant N/2+1 bins of a real signal's spectrum (numpy.fft.rfft) and
// IRFFT inverts it back to a real signal of a caller-specified length
// (numpy.fft.irfft). The butterfly loops live in an internal kernels package
// (scalar pure-Go now) so that SIMD kernels generated by go-asmgen across the
// six 64-bit Go targets (amd64, arm64, riscv64, loong64, ppc64le, s390x) can
// drop in later without changing the public API. See docs/plan-fft.md for the
// full roadmap.
package fft
