package fft

import "math"

// pow2StockhamMaxDefault routes every power of two to the Stockham engine on
// arm64, where it measured faster than the iterative pow2 kernel at every size
// (M4 Max: 256 1.07×, 1024 1.30×, 4096 1.10×, 65536 1.34×). That was with the
// passes in Go; they now run as NEON kernels, which only widens the gap.
//
// The Stockham passes on arm64. Every radix-2, 3, 4, 5 and 8 pass, and every
// radix-2, 3, 4 and 5 final pass with an even number of blocks, runs on a NEON
// kernel (internal/kernels/stockham_arm64.go, generated by go-asmgen); radix 7,
// the general radix and a final pass with an odd block count stay in Go. There
// is no stride or size limit: measured pass by pass on Neoverse-N1 (cfarm424,
// idle), the kernels ran 1.09–1.61× as fast as the Go passes on every pass of
// every length tried, the final passes 1.00–1.43×; end to end, every go-fft
// row of the parity harness gained 1.13–1.51× (geometric mean 1.28). On an
// Apple M4 Max (shared, load 3–4) no row lost: 1.01–1.40× (geometric mean
// 1.15), the largest rows within the noise. Pass by pass, though, some radix-4
// passes from 16384 points whose streams are 8 KB or more apart lost there,
// down to 0.70×: by all appearances a false store-to-load dependence through
// the 576-byte scratch gap (see offTheSets), which a gap of 2112 bytes or
// more removed on the M4 and did not change on N1. The gap was left as it is
// (Round 18 of BENCHMARKS.md, 2026-10-05).
func pow2StockhamMaxDefault() int { return math.MaxInt }

// r8MaxPow2Default and pow2OneRadix8Max factor a power of two 2^e on arm64 as radix-4
// passes, opening with one radix-8 pass when e is odd (never a lone radix-2
// pass). Three rules were timed at every 2^e from 32 to 8192 (2026-09-30):
// A, radix 8 as far as it goes (the rule amd64 keeps); B, radix 4 with a
// radix-2 pass for an odd e; C, this one. Time over the best of the three,
// geometric mean over both CPUs and all sizes: A 1.121 (worst 1.51), B 1.089
// (worst 1.26), C 1.022 (worst 1.11) — Apple M4 and Neoverse-N1 agree. Lengths
// with an odd factor keep rule A, which is neutral or better there.
//
// Above 8192, where those timings stop, rule B is kept: re-timed from 2^13 to
// 2^20, C lost on the M4 at 2^15 (1.19–1.25× B's time, also seen as a 0.87×
// RFFT 65536 end to end), while on Neoverse-N1 it won by only 3–11%. (The even
// exponents, which factor identically under B and C, put the M4's noise at
// ±10% during that run.)
func r8MaxPow2Default() int { return 0 }

const pow2OneRadix8Max = 8192

// oddRadicesFirstDefault keeps the pocketfft order here (powers of two first,
// odd primes last): the odd-first order was measured on amd64 only (see
// route_amd64.go).
func oddRadicesFirstDefault() bool { return false }

// parMinChunkDefault is the 8192 elements chosen in 2026-09 (BENCHMARKS.md,
// Round 3), kept here: the change of Round 17 was measured on amd64 only.
func parMinChunkDefault() int { return 1 << 13 }
