package fft

import "math"

// pow2StockhamMaxDefault routes every power of two to the Stockham engine on
// arm64, where it measured faster than the iterative pow2 kernel at every size
// (M4 Max: 256 1.07×, 1024 1.30×, 4096 1.10×, 65536 1.34×). That was with the
// passes in Go; they now run as NEON kernels, which only widens the gap.
//
// The Stockham passes on arm64. Every radix-2, 3, 4, 5 and 8 pass, and every
// radix-2, 3, 4 and 5 final pass with an even number of blocks, runs on a NEON
// kernel (internal/kernels/stockham_arm64.go, generated by go-asmgen); radix 7,
// the general radix and a final pass with an odd block count stay in Go. There
// is no stride or size limit: measured pass by pass on Neoverse-N1 (cfarm424,
// idle), the kernels ran 1.09–1.61× as fast as the Go passes on every pass of
// every length tried, the final passes 1.00–1.43×; end to end, every go-fft
// row of the parity harness gained 1.13–1.51× (geometric mean 1.28). On an
// Apple M4 Max (shared, load 3–4) no row lost: 1.01–1.40× (geometric mean
// 1.15), the largest rows within the noise. Pass by pass, though, some radix-4
// passes from 16384 points whose streams are 8 KB or more apart lost there,
// down to 0.70×: by all appearances a false store-to-load dependence through
// the 576-byte scratch gap (see offTheSets), which a gap of 2112 bytes or
// more removed on the M4 and did not change on N1. The gap was left as it is
// (Round 18 of BENCHMARKS.md, 2026-10-05).
//
// Since Round 21 a power of two keeps its data block-split between passes
// (kernels.StockhamSplitModes), so only its first pass deinterleaves and only
// its last interleaves: on Neoverse-N1, main time ÷ new time 1.07 (2^18) to
// 1.24 (2048), the same bits. The columns of an N-D transform run as strips of
// batched NEON passes (PlanN's stripAxes) instead of being gathered.
func pow2StockhamMaxDefault() int { return math.MaxInt }

// r8MaxPow2Default and pow2OneRadix8Max factor a power of two 2^e on arm64 as radix-4
// passes, opening with one radix-8 pass when e is odd (never a lone radix-2
// pass). Three rules were timed at every 2^e from 32 to 8192 (2026-09-30):
// A, radix 8 as far as it goes (the rule amd64 keeps); B, radix 4 with a
// radix-2 pass for an odd e; C, this one. Time over the best of the three,
// geometric mean over both CPUs and all sizes: A 1.121 (worst 1.51), B 1.089
// (worst 1.26), C 1.022 (worst 1.11) — Apple M4 and Neoverse-N1 agree. Lengths
// with an odd factor keep rule A, which is neutral or better there.
//
// Above 8192, where those timings stop, rule B is kept: re-timed from 2^13 to
// 2^20, C lost on the M4 at 2^15 (1.19–1.25× B's time, also seen as a 0.87×
// RFFT 65536 end to end), while on Neoverse-N1 it won by only 3–11%. (The even
// exponents, which factor identically under B and C, put the M4's noise at
// ±10% during that run.)
func r8MaxPow2Default() int { return 0 }

const pow2OneRadix8Max = 8192

// oddRadicesFirstDefault keeps the pocketfft order here (powers of two first,
// odd primes last) for the float32 plans, which measured it mixed (Round 22).
// complex128 plans take the odd-first order on arm64 since Round 24
// (compOddFirst, comp_route_arm64.go).
func oddRadicesFirstDefault() bool { return false }

// parMinChunkDefault is the 8192 elements chosen in 2026-09 (BENCHMARKS.md,
// Round 3). On arm64 it is the threshold that changed (parThresholdNDefault):
// raising the floor instead, as amd64 did in Round 17, cost Neoverse-N1 13%
// at 256×256 (4 goroutines instead of 8: 884 against 777 µs, 2026-10-05).
func parMinChunkDefault() int { return 1 << 13 }

// parThresholdNDefault is 65536 elements: a complex128 PlanN (FFT2, FFTN) of
// fewer elements, 2-D smaller than 256×256, runs on one goroutine. On Neoverse-N1 (cfarm424, 64 cores, all of them,
// median of seven rounds, 2026-10-05) splitting less than that work lost
// wherever it split: 128×128 took 357 µs on two goroutines against 211 µs on
// one; 128×256 516 (four) and 642 (two) against 480; 192×192 579 and 730
// against 553. From 256×256 more goroutines won: 777 µs on eight against 1142
// on one, and 512×512 1.63 ms against 4.80. (BENCHMARKS.md, Round 21.)
func parThresholdNDefault() int { return 1 << 16 }

// cascadeMinDefault is 0: the blocked schedule (cascade.go) was measured on
// amd64 only, so every length runs breadth first here.
func cascadeMinDefault() int { return 0 }
