package kernels

var useAVX2 = supportsAVX2()

// amd64 butterfly stage kernels generated by go-asmgen (butterfly_amd64.s).
// SSE2 is the baseline. AVX2 pairs adjacent butterflies when the CPU and OS
// support YMM state: even-span radix-4 stages and pairs of span-one radix-2
// groups. Other shapes retain SSE2. No kernel uses FMA or reassociates sums.
//
//go:generate sh -c "cd asmgen/amd64 && GOFLAGS=-mod=mod go run gen.go && mv cmul_amd64.s ../../cmul_amd64.s && mv butterfly_amd64.s ../../butterfly_amd64.s"

// These kernels ARE routed onto the FFT hot path (UseSIMDButterfly is true on
// amd64): the packed SSE2 ADDPD/SUBPD compute the butterfly's re and im in one
// instruction (2× the scalar throughput, since GOAMD64=v1 Go does not
// autovectorize the scalar loop), and they were measured to beat the inline
// scalar stage on the power-of-two and smooth-composite mid-range — the band
// BENCHMARKS.md flags as lagging FFTW. Bit-identity with the scalar oracle is
// preserved: MULPD/ADDPD are SEPARATELY rounded, matching the non-fused
// GOAMD64=v1 oracle (no FMA, no 1-ULP divergence), and the ∓i rotation is an
// exact SHUFPD lane swap + XORPD sign flip. The amd64 CI execution job asserts
// this bit-identity (TestRadix*StageMatchesScalar).

// radix2StageSIMD runs one radix-2 DIT pass, pairing leaf groups on AVX2.
func radix2StageSIMD(a []complex128, n, span int, tw []complex128) {
	if useAVX2 && span == 1 && n%4 == 0 {
		radix2LeafAVX2(&a[0], n, &tw[0])
		return
	}
	radix2StageSSE2(&a[0], n, span, &tw[0])
}

// radix4StageSIMD runs one radix-4 DIT pass with the supported vector width,
// selecting the forward or inverse rotation variant.
func radix4StageSIMD(a []complex128, n, span int, w1, w2, w3 []complex128, inverse bool) {
	// AVX2 handles two adjacent positions. Odd spans retain the SSE2 path.
	if useAVX2 && span%2 == 0 {
		if inverse {
			radix4StageAVX2Inv(&a[0], n, span, &w1[0], &w2[0], &w3[0])
		} else {
			radix4StageAVX2Fwd(&a[0], n, span, &w1[0], &w2[0], &w3[0])
		}
		return
	}
	if inverse {
		radix4StageSSE2Inv(&a[0], n, span, &w1[0], &w2[0], &w3[0])
		return
	}
	radix4StageSSE2Fwd(&a[0], n, span, &w1[0], &w2[0], &w3[0])
}

//go:noescape
func radix2StageSSE2(a *complex128, n, span int, tw *complex128)

//go:noescape
func radix4StageSSE2Fwd(a *complex128, n, span int, w1, w2, w3 *complex128)

//go:noescape
func radix4StageSSE2Inv(a *complex128, n, span int, w1, w2, w3 *complex128)

//go:noescape
func radix4StageAVX2Fwd(a *complex128, n, span int, w1, w2, w3 *complex128)

//go:noescape
func radix4StageAVX2Inv(a *complex128, n, span int, w1, w2, w3 *complex128)

func supportsAVX2() bool

//go:noescape
func radix2LeafAVX2(a *complex128, n int, tw *complex128)
