package kernels

var useAVX2 = supportsAVX2()

// amd64 butterfly stage kernels generated by go-asmgen (butterfly_amd64.s), for
// the iterative pow2 kernel. They are SSE2 only: that kernel runs on amd64 only
// when the CPU lacks AVX2, since with AVX2 every power of two goes to the
// Stockham engine (route_amd64.go). AVX2 stage kernels existed, but became
// unreachable outside the tests when that route changed (v0.1.3) and were
// removed (v0.1.8). No kernel uses FMA or reassociates sums.
//
// useAVX2 gates the Stockham AVX2 kernels (stockham_amd64.go).
//
//go:generate sh -c "cd asmgen/amd64 && GOFLAGS=-mod=mod go run gen.go && mv cmul_amd64.s ../../cmul_amd64.s && mv butterfly_amd64.s ../../butterfly_amd64.s && mv cpu_amd64.s ../../cpu_amd64.s"

// These kernels ARE routed onto the FFT hot path (UseSIMDButterfly is true on
// amd64): the packed SSE2 ADDPD/SUBPD compute the butterfly's re and im in one
// instruction (2× the scalar throughput, since GOAMD64=v1 Go does not
// autovectorize the scalar loop), and they were measured to beat the inline
// scalar stage on the power-of-two and smooth-composite mid-range — the band
// BENCHMARKS.md flags as lagging FFTW. Bit-identity with the scalar oracle is
// preserved: MULPD/ADDPD are SEPARATELY rounded, matching the non-fused
// GOAMD64=v1 oracle (no FMA, no 1-ULP divergence), and the ∓i rotation is an
// exact SHUFPD lane swap + XORPD sign flip. The amd64 CI execution job asserts
// this bit-identity (TestRadix*StageMatchesScalar).

// radix2StageSIMD runs one radix-2 DIT pass.
func radix2StageSIMD(a []complex128, n, span int, tw []complex128) {
	radix2StageSSE2(&a[0], n, span, &tw[0])
}

// radix4StageSIMD runs one radix-4 DIT pass, selecting the forward or inverse
// rotation variant.
func radix4StageSIMD(a []complex128, n, span int, w1, w2, w3 []complex128, inverse bool) {
	if inverse {
		radix4StageSSE2Inv(&a[0], n, span, &w1[0], &w2[0], &w3[0])
		return
	}
	radix4StageSSE2Fwd(&a[0], n, span, &w1[0], &w2[0], &w3[0])
}

//go:noescape
func radix2StageSSE2(a *complex128, n, span int, tw *complex128)

//go:noescape
func radix4StageSSE2Fwd(a *complex128, n, span int, w1, w2, w3 *complex128)

//go:noescape
func radix4StageSSE2Inv(a *complex128, n, span int, w1, w2, w3 *complex128)

func supportsAVX2() bool
