package kernels

// CMulScalar computes the elementwise (Hadamard) complex product a[i] *= b[i]
// over the first min(len(a), len(b)) elements, in place in a. It is the
// portable pure-Go correctness oracle for the pointwise complex multiply used
// by Bluestein's convolution, and the fallback when no SIMD kernel is selected
// for the running CPU.
//
// The complex product of (ar + ai·i) and (br + bi·i) is
//
//	(ar·br − ai·bi) + (ar·bi + ai·br)·i.
//
// Keeping this in its own function lets the SIMD variants (cmul_<arch>.s,
// generated by go-asmgen) drop in behind CMul with bit-identical results.
func CMulScalar(a, b []complex128) {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		ar, ai := real(a[i]), imag(a[i])
		br, bi := real(b[i]), imag(b[i])
		a[i] = complex(ar*br-ai*bi, ar*bi+ai*br)
	}
}
