package kernels

// CMulScalar computes the elementwise (Hadamard) complex product a[i] *= b[i]
// over the first min(len(a), len(b)) elements, in place in a. It is the
// portable pure-Go correctness oracle for the pointwise complex multiply used
// by Bluestein's convolution, and the fallback when no SIMD kernel is selected
// for the running CPU.
//
// The complex product of (ar + ai·i) and (br + bi·i) is
//
//	(ar·br − ai·bi) + (ar·bi + ai·br)·i.
//
// Keeping this in its own function lets the SIMD variants (cmul_<arch>.s,
// generated by go-asmgen) drop in behind CMul with bit-identical results.
//
// //go:noinline pins a single compiled body for the oracle so that every
// caller — the dispatched CMul, the per-arch cmulSIMD fallback, and the test's
// reference computation — observes the SAME floating-point form. Without it the
// gc compiler may fuse ar*br-ai*bi into an FMA at one call site but not another
// (FMA is baseline on arm64 and the other non-amd64 targets), making the
// scalar==scalar comparison diverge by 1 ULP purely from inlining. amd64's SSE2
// kernel matches because GOAMD64=v1 does not fuse, the same form this body
// compiles to there.
//
//go:noinline
func CMulScalar(a, b []complex128) {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		ar, ai := real(a[i]), imag(a[i])
		br, bi := real(b[i]), imag(b[i])
		a[i] = complex(ar*br-ai*bi, ar*bi+ai*br)
	}
}
