package kernels

// s390x: a z/Architecture vector-facility pointwise-complex-multiply kernel
// generated by go-asmgen (cmul_s390x.s). The vector facility (z13+) is part of
// the s390x baseline the Go toolchain requires, so cmulSIMD is always callable —
// there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/s390x && GOFLAGS=-mod=mod go run gen.go && mv cmul_s390x.s ../../cmul_s390x.s"

// The kernel is a validated correctness artifact: the per-arch CI execution job
// (qemu-s390x) asserts cmulSIMD is bit-identical to CMulScalar. It is not routed
// onto the FFT hot path (CMul stays scalar) because the compiler's
// autovectorized scalar loop is already at least as fast at this width; the SIMD
// kernel is kept for its per-arch validation and as the reference implementation
// for future widening.
//
// s390x is the project's only BIG-ENDIAN target, which is exactly why a
// bit-identical SIMD kernel here is the highest-value validation: the
// VL/VMRHG/VMRLG/VST deinterleave-compute-interleave must pair correctly under
// big-endian lane order, and the per-arch qemu job proves it does.
//
// Bit-identity, and how it differs from amd64. FMA is baseline on s390x, so the
// gc compiler emits a FUSED form for the scalar oracle (FMUL then FMSUB for the
// real part ar*br-ai*bi; FMUL then FMADD for the imaginary part ar*bi+ai*br;
// confirmed by disassembling CMulScalar). The vector kernel reproduces exactly
// that fusion two-lane: VFMDB computes each product (exactly-rounded multiply,
// matching the oracle's FMUL) and VFMSDB/VFMADB fold in the second term (the
// fused subtract/add the oracle performs). A non-fused vector kernel — or one
// whose fusion form differed — would diverge by up to 1 ULP; the random
// SIMD-vs-scalar test would catch it. (amd64's SSE2 kernel, by contrast, is
// bit-identical via SEPARATELY rounded MULPD+ADDPD, because its GOAMD64=v1 oracle
// does not fuse; arm64's NEON kernel matches arm64's FMSUBD/FMADDD fusion.)

// cmulSIMD multiplies a[i] *= b[i] using the vector kernel (two complex128 per
// iteration, scalar tail for an odd element), matching CMulScalar exactly.
func cmulSIMD(a, b []complex128) {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	if n == 0 {
		return
	}
	cmulVX(&a[0], &b[0], n)
}

//go:noescape
func cmulVX(a, b *complex128, n int)
