package kernels

import (
	"os"
	"strings"
)

// riscv64: an RVV 1.0 (RISC-V Vector) pointwise-complex-multiply kernel
// generated by go-asmgen (cmul_riscv64.s). Unlike amd64/arm64/s390x, where the
// SIMD instruction set is part of the architecture baseline the Go toolchain
// requires, the V extension is OPTIONAL on riscv64 — so cmulSIMD MUST probe for
// it at run time and fall back to the scalar oracle when V is absent. Calling
// the RVV kernel on a non-V CPU would raise SIGILL (VSETVLI is illegal there).
//
//go:generate sh -c "cd asmgen/riscv64 && GOFLAGS=-mod=mod go run gen.go && mv cmul_riscv64.s ../../cmul_riscv64.s"
//
// The kernel is hardware-validated: it was proven bit-for-bit identical to
// CMulScalar on REAL RVV 1.0 hardware — cfarm95 on the GCC Compile Farm, a
// SpacemiT X60 (RVA22 + RVV 1.0, isa string includes `v`/`zve64d`) — where the
// SIMD-vs-scalar test RUNS (not skips) and passes on structured and random
// inputs across a sweep of lengths. The project's CI runs riscv64 under a
// non-V qemu-riscv64 CPU, where this dispatch takes the scalar path and the
// SIMD-vs-scalar test SKIPs its RVV comparison (so CI stays green; the RVV
// instructions never execute there).
//
// It is not routed onto the FFT hot path (CMul stays scalar) because the
// compiler's autovectorized scalar loop is already at least as fast at this
// width; the SIMD kernel is kept for its hardware validation and as the
// reference implementation for future widening.
//
// Bit-identity. FMA is baseline on riscv64, so the gc compiler emits a FUSED
// form for the scalar oracle (FMULD then FNMSUBD for the real part
// ar*br-ai*bi; FMULD then FMADDD for the imaginary part ar*bi+ai*br; confirmed
// by disassembling CMulScalar with -gcflags=-S). The RVV kernel reproduces
// exactly that fusion vl-wide — VFMUL.VV computes each product (exactly-rounded
// multiply, matching the oracle's FMULD) and VFNMSAC.VV/VFMACC.VV fold in the
// second term (the fused subtract/add the oracle performs). It is the precise
// RVV analogue of the arm64 NEON kernel. A non-fused kernel — or one whose
// fusion form differed — would diverge by up to 1 ULP; the random
// SIMD-vs-scalar test on cfarm95 would catch it.

// haveRVV reports whether the running riscv64 CPU implements the V (vector)
// extension, i.e. whether cmulRVV is safe to call. It parses /proc/cpuinfo's
// isa string and looks for the standalone `v` extension token (or a zve64*
// vector subset that also provides the VLSEG2E64V/VFMACC.VV double-precision
// vector ops this kernel uses). The probe is computed once; on any read error
// or non-Linux platform it returns false, so the scalar path is taken (this is
// also what makes CI's non-V qemu safe — the RVV instructions never execute).
var haveRVV = detectRVV()

func detectRVV() bool {
	data, err := os.ReadFile("/proc/cpuinfo")
	if err != nil {
		return false
	}
	for _, line := range strings.Split(string(data), "\n") {
		key, val, ok := strings.Cut(line, ":")
		if !ok || strings.TrimSpace(key) != "isa" {
			continue
		}
		return isaHasV(strings.TrimSpace(val))
	}
	return false
}

// isaHasV reports whether a RISC-V isa string advertises the V vector extension:
// either the standalone single-letter `v` in the base ISA string
// (e.g. "rv64imafdcv...") or a zve64{d,f,x} double-capable vector subset. It
// tokenises on `_`. For the base token it strips the "rv32"/"rv64"/"rv128"
// width prefix FIRST — otherwise the `v` in the "rv" prefix itself would be a
// false positive — then looks for a standalone `v` among the single-letter
// extensions. A false positive here is a SIGILL on a non-V CPU (CI's qemu), so
// this is deliberately strict; see TestISAHasV.
func isaHasV(isa string) bool {
	isa = strings.ToLower(isa)
	for _, tok := range strings.Split(isa, "_") {
		// zve64d/zve64f/zve64x: the double-capable embedded vector subsets that
		// still provide the e64 segment loads and VFMACC.VV this kernel needs.
		// (zve32* is 32-bit-element only and is intentionally NOT accepted.)
		if strings.HasPrefix(tok, "zve64") {
			return true
		}
		// The base ISA token (e.g. "rv64imafdcv"): strip the width prefix so the
		// "v" in "rv" is not mistaken for the V extension, then look for a
		// standalone single-letter "v".
		base := tok
		for _, p := range []string{"rv64", "rv32", "rv128"} {
			if strings.HasPrefix(base, p) {
				base = base[len(p):]
				if strings.IndexByte(base, 'v') >= 0 {
					return true
				}
				break
			}
		}
	}
	return false
}

// cmulSIMD multiplies a[i] *= b[i] using the RVV kernel when the running CPU has
// the V extension, matching CMulScalar exactly; otherwise it falls back to the
// scalar oracle (so it is always safe to call, including under CI's non-V qemu).
func cmulSIMD(a, b []complex128) {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	if n == 0 {
		return
	}
	if !haveRVV {
		CMulScalar(a, b)
		return
	}
	cmulRVV(&a[0], &b[0], n)
}

//go:noescape
func cmulRVV(a, b *complex128, n int)
