package kernels

// amd64: an SSE2 pointwise-complex-multiply kernel generated by go-asmgen
// (cmul_amd64.s). SSE2 is part of the amd64 baseline the Go toolchain requires,
// so cmulSIMD is always callable — there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/amd64 && GOFLAGS=-mod=mod go run gen.go && mv cmul_amd64.s ../../cmul_amd64.s"

// The kernel is a validated correctness artifact: the per-arch CI execution job
// asserts cmulSIMD is bit-identical to CMulScalar. It is not routed onto the
// FFT hot path (CMul stays scalar) because the compiler's autovectorized scalar
// loop is already at least as fast at this width; the SIMD kernel is kept for
// its per-arch validation and as the reference implementation for future
// widening.
//
// The SSE2 kernel is bit-identical to CMulScalar: MULPD computes the two
// products with the same rounding as the scalar multiplies, XORPD flips a sign
// exactly, and ADDPD rounds the sum exactly as the scalar add/sub does. No
// fused multiply-add is used, so there is no 1-ULP divergence.

// cmulSIMD multiplies a[i] *= b[i] using the SSE2 kernel (one complex128 per
// iteration), matching CMulScalar exactly.
func cmulSIMD(a, b []complex128) {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	if n == 0 {
		return
	}
	cmulSSE2(&a[0], &b[0], n)
}

//go:noescape
func cmulSSE2(a, b *complex128, n int)
