package kernels

// arm64: a NEON pointwise-complex-multiply kernel generated by go-asmgen
// (cmul_arm64.s). NEON (ASIMD) is part of the arm64 baseline the Go toolchain
// requires, so cmulSIMD is always callable — there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/arm64 && GOFLAGS=-mod=mod go run gen.go && mv cmul_arm64.s ../../cmul_arm64.s"

// The kernel is a validated correctness artifact: the per-arch CI execution job
// asserts cmulSIMD is bit-identical to CMulScalar. It is not routed onto the
// FFT hot path (CMul stays scalar) because the compiler's autovectorized scalar
// loop is already at least as fast at this width; the SIMD kernel is kept for
// its per-arch validation and as the reference implementation for future
// widening.
//
// Bit-identity, and how it differs from amd64. FMA is baseline on arm64, so the
// gc compiler emits a FUSED form for the scalar oracle (FMSUBD for the real
// part's ar*br-ai*bi, FMADDD for the imaginary part's ar*bi+ai*br; confirmed by
// disassembling CMulScalar). The NEON kernel reproduces exactly that fusion: it
// processes two complex128 per iteration with VLD2/VST2 deinterleave, computing
// each product into a zeroed accumulator with VFMLA (adding +0.0 leaves the
// product's rounding unchanged, matching the oracle's FMULD) and folding in the
// second term with VFMLS / VFMLA (the fused subtract / add the oracle performs).
// A non-fused NEON kernel — or one whose fusion form differed — would diverge by
// up to 1 ULP; the random SIMD-vs-scalar test would catch it. (amd64's SSE2
// kernel, by contrast, is bit-identical via SEPARATELY rounded MULPD+ADDPD,
// because its GOAMD64=v1 oracle does not fuse.)

// cmulSIMD multiplies a[i] *= b[i] using the NEON kernel (two complex128 per
// iteration, scalar tail for an odd element), matching CMulScalar exactly.
func cmulSIMD(a, b []complex128) {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	if n == 0 {
		return
	}
	cmulNEON(&a[0], &b[0], n)
}

//go:noescape
func cmulNEON(a, b *complex128, n int)
