// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·cmulRVV(SB), NOSPLIT, $0-24
	MOV a+0(FP), X5
	MOV b+8(FP), X6
	MOV n+16(FP), X7
	loop:
	BEQZ X7, done
	VSETVLI X7, E64, M1, TA, MA, X10
	VLSEG2E64V (X5), V8
	VLSEG2E64V (X6), V10
	VFMULVV V8, V10, V12
	VFNMSACVV V9, V11, V12
	VFMULVV V8, V11, V13
	VFMACCVV V9, V10, V13
	VSSEG2E64V V12, (X5)
	SLLI $4, X10, X11
	ADD X11, X5
	ADD X11, X6
	SUB X10, X7
	JMP loop
	done:
	RET

