// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·cmulNEON(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	loop2:
	CMP $2, R2
	BLT tail
	VLD2 (R0), [V0.D2, V1.D2]
	VLD2 (R1), [V2.D2, V3.D2]
	VEOR V4.B16, V4.B16, V4.B16
	VEOR V5.B16, V5.B16, V5.B16
	VFMLA V2.D2, V0.D2, V4.D2
	VFMLS V3.D2, V1.D2, V4.D2
	VFMLA V3.D2, V0.D2, V5.D2
	VFMLA V2.D2, V1.D2, V5.D2
	VST2 [V4.D2, V5.D2], (R0)
	ADD $32, R0
	ADD $32, R1
	SUB $2, R2
	B loop2
	tail:
	CBZ R2, done
	FMOVD (R0), F0
	FMOVD 8(R0), F1
	FMOVD (R1), F2
	FMOVD 8(R1), F3
	FMULD F2, F0, F4
	FMSUBD F1, F4, F3, F4
	FMULD F3, F0, F5
	FMADDD F2, F5, F1, F5
	FMOVD F4, (R0)
	FMOVD F5, 8(R0)
	done:
	RET

