package kernels

// The radix-10, -15 and -20 pass kernels (Round 26), generated by go-asmgen
// into comp2_amd64.s (asmgen/amd64/gen.go, genComp2File): the fft package's
// radix5q.go, the prime-factor algorithm for r = 5·q. StockhamPass runs them
// with the other AVX2 kernels; they read the twiddle table StockhamTwiddles
// builds.

//go:noescape
func skPass10AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast10AVX2(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skPass15AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast15AVX2(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skPass20AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast20AVX2(cc, ch *complex128, k *float64, l1 int)
