// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·supportsAVX2(SB), NOSPLIT, $0-1
	MOVB $0, ret+0(FP)
	XORL AX, AX
	CPUID
	CMPL AX, $7
	JL supportsAVX2_unsupported
	MOVL $1, AX
	CPUID
	ANDL $0x18000000, CX // AVX and OSXSAVE
	CMPL CX, $0x18000000
	JNE supportsAVX2_unsupported
	XORL CX, CX
	XGETBV
	ANDL $6, AX // XMM and YMM state enabled in XCR0
	CMPL AX, $6
	JNE supportsAVX2_unsupported
	MOVL $7, AX
	XORL CX, CX
	CPUID
	TESTL $0x20, BX // AVX2
	JZ supportsAVX2_unsupported
	MOVB $1, ret+0(FP)
supportsAVX2_unsupported:
	RET

