// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·supportsAVX2(SB), NOSPLIT, $0-1
	MOVB $0, ret+0(FP)
	XORL AX, AX
	CPUID
	CMPL AX, $7
	JL supportsAVX2_unsupported
	MOVL $1, AX
	CPUID
	ANDL $0x18000000, CX // AVX and OSXSAVE
	CMPL CX, $0x18000000
	JNE supportsAVX2_unsupported
	XORL CX, CX
	XGETBV
	ANDL $6, AX // XMM and YMM state enabled in XCR0
	CMPL AX, $6
	JNE supportsAVX2_unsupported
	MOVL $7, AX
	XORL CX, CX
	CPUID
	TESTL $0x20, BX // AVX2
	JZ supportsAVX2_unsupported
	MOVB $1, ret+0(FP)
supportsAVX2_unsupported:
	RET

TEXT ·supportsAVX512F(SB), NOSPLIT, $0-1
	MOVB $0, ret+0(FP)
	XORL AX, AX
	CPUID
	CMPL AX, $7
	JL supportsAVX512F_unsupported
	MOVL $1, AX
	CPUID
	ANDL $0x18000000, CX // AVX and OSXSAVE
	CMPL CX, $0x18000000
	JNE supportsAVX512F_unsupported
	XORL CX, CX
	XGETBV
	ANDL $0xE6, AX // XMM, YMM, opmask, ZMM_Hi256 and Hi16_ZMM state in XCR0
	CMPL AX, $0xE6
	JNE supportsAVX512F_unsupported
	MOVL $7, AX
	XORL CX, CX
	CPUID
	TESTL $0x10000, BX // AVX512F
	JZ supportsAVX512F_unsupported
	MOVB $1, ret+0(FP)
supportsAVX512F_unsupported:
	RET

TEXT ·isGenuineIntel(SB), NOSPLIT, $0-1
	MOVB $0, ret+0(FP)
	XORL AX, AX
	CPUID
	CMPL BX, $0x756e6547 // "Genu"
	JNE isGenuineIntel_other
	CMPL DX, $0x49656e69 // "ineI"
	JNE isGenuineIntel_other
	CMPL CX, $0x6c65746e // "ntel"
	JNE isGenuineIntel_other
	MOVB $1, ret+0(FP)
isGenuineIntel_other:
	RET

