// Package kernels holds the inner loops of the FFT — the bit-reversal
// permutation and the radix-2 butterfly stages — isolated from the public API.
//
// Today these are portable scalar pure-Go implementations. They are kept in
// their own package so that SIMD variants generated by go-asmgen across the six
// 64-bit Go targets (amd64, arm64, riscv64, loong64, ppc64le, s390x) can be
// substituted later behind the same function signatures without touching the
// public fft package.
package kernels

import "math"

// IsPowerOfTwo reports whether n is a positive power of two.
func IsPowerOfTwo(n int) bool {
	return n > 0 && n&(n-1) == 0
}

// BitReverse permutes x in place into bit-reversal order, the prerequisite
// ordering for the iterative radix-2 transform. len(x) must be a power of two.
func BitReverse(x []complex128) {
	n := len(x)
	for i, j := 1, 0; i < n; i++ {
		bit := n >> 1
		for ; j&bit != 0; bit >>= 1 {
			j ^= bit
		}
		j ^= bit
		if i < j {
			x[i], x[j] = x[j], x[i]
		}
	}
}

// Radix2 performs an in-place iterative radix-2 Cooley–Tukey transform on x,
// which must already be in bit-reversal order and have a power-of-two length.
// When inverse is true it uses the conjugate twiddle factors; the caller is
// responsible for the 1/N normalization.
func Radix2(x []complex128, inverse bool) {
	n := len(x)
	sign := -1.0
	if inverse {
		sign = 1.0
	}
	for length := 2; length <= n; length <<= 1 {
		ang := sign * 2 * math.Pi / float64(length)
		wlen := complex(math.Cos(ang), math.Sin(ang))
		half := length >> 1
		for start := 0; start < n; start += length {
			w := complex(1, 0)
			for k := 0; k < half; k++ {
				u := x[start+k]
				v := x[start+k+half] * w
				x[start+k] = u + v
				x[start+k+half] = u - v
				w *= wlen
			}
		}
	}
}
