package kernels

// NEON Stockham pass kernels for the fft package's stockham.go, generated by
// go-asmgen into stockham_arm64.s (asmgen/arm64/gen.go, genStockhamPass4 and
// genStockhamLast4). They run the radix-4 pass two points per register and are
// bit-identical to the Go pass gc compiles on arm64, fused multiply-adds
// included: see gen.go for which products gc fuses and how the kernels match
// them. TestStockhamPassMatchesScalarNEON asserts it.

// UseStockhamNEON reports whether StockhamPass may take the NEON kernels. NEON
// is part of the arm64 baseline, so it is always true; it is a variable so the
// tests can run the Go passes for comparison.
var UseStockhamNEON = true

// StockhamTwiddles builds, for a pass of radix r with l1 earlier points and
// ido remaining ones, the twiddle table the NEON kernels read, in forward and
// conjugate form, or returns nils when no kernel runs that pass. root is the
// size-n root table (root[k] = exp(-2πi·k/n)); twiddle j of point i is
// root[(j·l1·i) mod n], i = 0..ido-1, j = 1..r-1.
//
// The table is one sequential stream in the order the kernels walk the points,
// two at a time and already split into real and imaginary parts: for the pair
// i, i+1 and each j, the float64s re(w_j(i)), re(w_j(i+1)), im(w_j(i)),
// im(w_j(i+1)), so a VLD1 loads them as they are used. It is stored as
// complex128 for the plan's sake; each element holds two of those float64s.
// For an odd ido the last point's pair is completed with zeros.
func StockhamTwiddles(r, ido, l1 int, root []complex128) (fwd, conj []complex128) {
	if ido < 2 || !stockhamNEON(r, ido, l1) {
		return nil, nil
	}
	n := len(root)
	fwd = make([]complex128, twLen(r, ido))
	conj = make([]complex128, len(fwd))
	at := 0
	for i := 0; i < ido; i += 2 {
		for j := 1; j < r; j++ {
			a, b := root[(j*l1*i)%n], complex128(0)
			if i+1 < ido {
				b = root[(j*l1*(i+1))%n]
			}
			fwd[at] = complex(real(a), real(b))
			fwd[at+1] = complex(imag(a), imag(b))
			conj[at] = fwd[at]
			conj[at+1] = complex(-imag(a), -imag(b))
			at += 2
		}
	}
	return fwd, conj
}

// stockhamNEON reports whether a NEON kernel runs a pass of radix r with ido
// points per block and l1 blocks: radix 2, 3, 4, 5 or 8 for ido >= 2 (points
// in pairs, an odd last one alone), and radix 2, 3, 4 or 5 with an even l1 for
// the final pass (ido == 1, blocks in pairs). Radix 7 and the general radix
// stay in Go.
func stockhamNEON(r, ido, l1 int) bool {
	if r >= len(skPassNEON) {
		return false
	}
	if ido == 1 {
		return skLastNEON[r] != nil && l1%2 == 0
	}
	return skPassNEON[r] != nil
}

// twLen is the length of a pass's twiddle table: r-1 twiddles for each of
// ido points rounded up to whole pairs.
func twLen(r, ido int) int { return (r - 1) * (ido + ido&1) }

type (
	skPassFn func(cc, ch, tw *complex128, ido, l1 int)
	skLastFn func(cc, ch *complex128, l1 int)
)

// The kernels by radix, forward and inverse.
var (
	skPassNEON    = [9]skPassFn{2: skPass2NEON, 3: skPass3NEON, 4: skPass4NEON, 5: skPass5NEON, 8: skPass8NEON}
	skPassNEONInv = [9]skPassFn{2: skPass2NEONInv, 3: skPass3NEONInv, 4: skPass4NEONInv, 5: skPass5NEONInv, 8: skPass8NEONInv}
	skLastNEON    = [9]skLastFn{2: skLast2NEON, 3: skLast3NEON, 4: skLast4NEON, 5: skLast5NEON}
	skLastNEONInv = [9]skLastFn{2: skLast2NEONInv, 3: skLast3NEONInv, 4: skLast4NEONInv, 5: skLast5NEONInv}
)

// StockhamPass runs one Stockham pass of radix r on a NEON kernel and reports
// true, or reports false (and does nothing) when no kernel runs it. cc holds
// r·ido·l1 inputs, ch receives as many outputs, and tw is the table
// StockhamTwiddles built for the pass (unused by the final pass, ido == 1).
// wide is the AVX-512 switch of amd64 and is ignored.
func StockhamPass(r, ido, l1 int, cc, ch, tw []complex128, inverse, wide bool) bool {
	if !UseStockhamNEON || !stockhamNEON(r, ido, l1) {
		return false
	}
	n := r * ido * l1
	_, _ = cc[n-1], ch[n-1] // the kernels trust these lengths
	if ido == 1 {
		last := skLastNEON[r]
		if inverse {
			last = skLastNEONInv[r]
		}
		last(&cc[0], &ch[0], l1)
		return true
	}
	_ = tw[twLen(r, ido)-1]
	pass := skPassNEON[r]
	if inverse {
		pass = skPassNEONInv[r]
	}
	pass(&cc[0], &ch[0], &tw[0], ido, l1)
	return true
}

// Untangle returns 0: the fft package untangles every bin in Go.
func Untangle(dst, z, tw []complex128, m int) int { return 0 }

// Retangle returns 0: the fft package rebuilds every bin in Go.
func Retangle(z, x, tw []complex128, m int, h float64) int { return 0 }

//go:noescape
func skPass3NEON(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass3NEONInv(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass4NEON(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass4NEONInv(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass5NEON(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass5NEONInv(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass8NEON(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass8NEONInv(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skLast3NEON(cc, ch *complex128, l1 int)

//go:noescape
func skLast3NEONInv(cc, ch *complex128, l1 int)

//go:noescape
func skLast4NEON(cc, ch *complex128, l1 int)

//go:noescape
func skLast4NEONInv(cc, ch *complex128, l1 int)

//go:noescape
func skLast5NEON(cc, ch *complex128, l1 int)

//go:noescape
func skLast5NEONInv(cc, ch *complex128, l1 int)

//go:noescape
func skPass2NEON(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skPass2NEONInv(cc, ch, tw *complex128, ido, l1 int)

//go:noescape
func skLast2NEON(cc, ch *complex128, l1 int)

//go:noescape
func skLast2NEONInv(cc, ch *complex128, l1 int)
