package kernels

import "math"

// Stockham pass kernels for the fft package's stockham.go, generated by
// go-asmgen into butterfly_amd64.s (asmgen/amd64/gen.go, genStockhamAVX2). They
// run a whole pass of radix 2, 3, 4, 5 or 8 two points per YMM register, and are
// bit-identical to stockham.go's scalar passes built for GOAMD64=v1: the same
// operations in the same order, separately rounded (no FMA), the rotations as
// exact lane swaps and sign flips, and the untwiddled i = 0 point restored by a
// blend rather than multiplied by one. TestStockhamPassMatchesScalar asserts it.

// UseStockhamAVX2 reports whether StockhamPass takes the AVX2 kernels. It is a
// variable so the tests can run the scalar passes on an AVX2 machine too.
var UseStockhamAVX2 = useAVX2

// skConst holds the kernels' constants, one 32-byte row each (the offsets are
// the k* constants in gen.go): row 0 is the ±i rotation sign mask, which is
// what makes a table forward or inverse.
type skConst [8][4]float64

var skFwd, skInv = newSKConst(false), newSKConst(true)

func newSKConst(inverse bool) *skConst {
	neg := math.Copysign(0, -1)
	sign := [4]float64{0, neg, 0, neg} // rotS forward: (re,im) -> (im, -re)
	if inverse {
		sign = [4]float64{neg, 0, neg, 0} // inverse: (re,im) -> (-im, re)
	}
	row := func(v float64) [4]float64 { return [4]float64{v, v, v, v} }
	return &skConst{
		sign,
		row(0.5),
		row(0.8660254037844386467637231707529361834714026269051903140279), // sin(2π/3)
		row(0.30901699437494742410229341718281905886015458990288),         // cos(2π/5)
		row(-0.80901699437494742410229341718281905886015458990289),        // cos(4π/5)
		row(0.95105651629515357211643933337938214340569863412575),         // sin(2π/5)
		row(0.58778525229247312916870595463907276859765243764314),         // sin(4π/5)
		row(0.707106781186547524400844362104849),                          // √2/2
	}
}

// stockhamSIMD reports whether a kernel exists for radix r.
func stockhamSIMD(r int) bool {
	switch r {
	case 2, 3, 4, 5, 8:
		return true
	}
	return false
}

// StockhamTwiddles builds, for a pass of radix r with l1 earlier points and
// ido remaining ones, the twiddle table the kernel reads: root is the size-n
// root table (root[k] = exp(-2πi·k/n)), and block j-1 (j = 1..r-1) holds
// root[(j·l1·i) mod n] for i = 0..ido-1, in forward and conjugate form. It
// returns nils when no kernel will run that pass.
func StockhamTwiddles(r, ido, l1 int, root []complex128) (fwd, conj []complex128) {
	if !stockhamSIMD(r) || ido < 2 {
		return nil, nil
	}
	n := len(root)
	fwd = make([]complex128, (r-1)*ido)
	conj = make([]complex128, (r-1)*ido)
	for j := 1; j < r; j++ {
		for i := 0; i < ido; i++ {
			w := root[(j*l1*i)%n]
			fwd[(j-1)*ido+i] = w
			conj[(j-1)*ido+i] = complex(real(w), -imag(w))
		}
	}
	return fwd, conj
}

// StockhamPass runs one Stockham pass of radix r on the AVX2 kernels and
// reports true, or reports false (and does nothing) when it cannot: no AVX2 or
// a radix without a kernel. The final pass (ido == 1) takes its own kernels.
// cc holds r·ido·l1 inputs, ch receives as many outputs, and tw is the pass's
// twiddle table extended to i = 0: (r-1) blocks of ido entries.
func StockhamPass(r, ido, l1 int, cc, ch, tw []complex128, inverse bool) bool {
	if !UseStockhamAVX2 || !stockhamSIMD(r) {
		return false
	}
	n := r * ido * l1
	_, _ = cc[n-1], ch[n-1] // the kernels trust these lengths
	k := skFwd
	if inverse {
		k = skInv
	}
	if ido == 1 {
		// The final pass: no twiddles, vectorized across blocks.
		switch r {
		case 2:
			skLast2AVX2(&cc[0], &ch[0], k, l1)
		case 3:
			skLast3AVX2(&cc[0], &ch[0], k, l1)
		case 4:
			skLast4AVX2(&cc[0], &ch[0], k, l1)
		case 5:
			skLast5AVX2(&cc[0], &ch[0], k, l1)
		default:
			skLast8AVX2(&cc[0], &ch[0], k, l1)
		}
		return true
	}
	_ = tw[(r-1)*ido-1]
	switch r {
	case 2:
		skPass2AVX2(&cc[0], &ch[0], &tw[0], k, ido, l1)
	case 3:
		skPass3AVX2(&cc[0], &ch[0], &tw[0], k, ido, l1)
	case 4:
		skPass4AVX2(&cc[0], &ch[0], &tw[0], k, ido, l1)
	case 5:
		skPass5AVX2(&cc[0], &ch[0], &tw[0], k, ido, l1)
	default:
		skPass8AVX2(&cc[0], &ch[0], &tw[0], k, ido, l1)
	}
	return true
}

//go:noescape
func skPass2AVX2(cc, ch, tw *complex128, k *skConst, ido, l1 int)

//go:noescape
func skPass3AVX2(cc, ch, tw *complex128, k *skConst, ido, l1 int)

//go:noescape
func skPass4AVX2(cc, ch, tw *complex128, k *skConst, ido, l1 int)

//go:noescape
func skPass5AVX2(cc, ch, tw *complex128, k *skConst, ido, l1 int)

//go:noescape
func skPass8AVX2(cc, ch, tw *complex128, k *skConst, ido, l1 int)

//go:noescape
func skLast2AVX2(cc, ch *complex128, k *skConst, l1 int)

//go:noescape
func skLast3AVX2(cc, ch *complex128, k *skConst, l1 int)

//go:noescape
func skLast4AVX2(cc, ch *complex128, k *skConst, l1 int)

//go:noescape
func skLast5AVX2(cc, ch *complex128, k *skConst, l1 int)

//go:noescape
func skLast8AVX2(cc, ch *complex128, k *skConst, l1 int)

// UseUntangleAVX2 reports whether Untangle takes the AVX2 kernel; a variable so
// the tests can compare it with the scalar loop on an AVX2 machine.
var UseUntangleAVX2 = useAVX2

// Untangle runs the real-FFT untangle for bins k = 1 .. 2·⌊half/2⌋ (half =
// (m-1)/2) on the AVX2 kernel and returns the last bin it produced, or 0 when
// it did nothing; the caller finishes the remaining bins, and the DC, Nyquist
// and middle bins, in Go. dst has m+1 entries, z and tw at least m.
func Untangle(dst, z, tw []complex128, m int) int {
	pairs := (m - 1) / 2 / 2
	if !UseUntangleAVX2 || pairs == 0 {
		return 0
	}
	_, _, _ = dst[m], z[m-1], tw[2*pairs] // the kernel trusts these lengths
	untangleAVX2(&dst[0], &z[0], &tw[0], skFwd, m, pairs)
	return 2 * pairs
}

//go:noescape
func untangleAVX2(dst, z, tw *complex128, k *skConst, m, pairs int)

// Retangle runs the real-FFT inverse untangle for k = 1 .. 2·⌊half/2⌋ (half =
// (m-1)/2) on the AVX2 kernel, writing z from the complete half spectrum x
// scaled by h = 0.5·scale, and returns the last k it produced, or 0 when it did
// nothing (UseUntangleAVX2 gates it too). z and tw hold at least m entries, x m+1.
func Retangle(z, x, tw []complex128, m int, h float64) int {
	pairs := (m - 1) / 2 / 2
	if !UseUntangleAVX2 || pairs == 0 {
		return 0
	}
	_, _, _ = z[m-1], x[m], tw[2*pairs]
	hv := [4]float64{h, h, h, h}
	retangleAVX2(&z[0], &x[0], &tw[0], skFwd, &hv, m, pairs)
	return 2 * pairs
}

//go:noescape
func retangleAVX2(z, x, tw *complex128, k *skConst, h *[4]float64, m, pairs int)
