package kernels

// Single-precision (complex64) NEON Stockham pass kernels for the fft
// package's stockham32_passes.go, generated by go-asmgen into
// stockham32_arm64.s (asmgen/arm64/gen.go, genF32StockhamPass and
// genF32StockhamLast). They run four points per register pair and are
// bit-identical to the Go passes gc compiles on arm64, fused multiply-adds
// included (see gen.go). TestStockham32PassMatchesScalar asserts it.

// UseStockham32 reports whether StockhamPass32 may take the NEON kernels.
// NEON is part of the arm64 baseline, so it is always true; it is a variable
// so the tests can run the Go passes for comparison.
var UseStockham32 = true

// StockhamTwiddles32 builds, for a float32 pass of radix r with l1 earlier
// points and ido remaining ones, the twiddle table the NEON kernels read, in
// forward and conjugate form, or returns nils when no kernel runs the pass.
// Twiddle j of point i is root[(j·l1·i) mod n] rounded once to complex64, i =
// 0..ido-1, j = 1..r-1.
//
// The table is one sequential stream, already split into real and imaginary
// parts, in the groups the kernels walk the points (twGroups: fours, then a
// two and a one for ido mod 4): for a group of g points and each j, the g
// float32 real parts re(w_j(i0)) … re(w_j(i0+g-1)), then the g imaginary
// parts. It is stored as complex64 for the plan's sake, g of them per run, so
// it has (r-1)·ido entries; a lone point's run is its twiddle as it is.
func StockhamTwiddles32(r, ido, l1 int, root []complex128) (fwd, conj []complex64) {
	if ido < 2 || !stockham32Kernel(r, ido, l1) {
		return nil, nil
	}
	n := len(root)
	f := make([]float32, 2*(r-1)*ido)
	c := make([]float32, len(f))
	at, i0 := 0, 0
	for _, g := range twGroups(ido) {
		for j := 1; j < r; j++ {
			for q := 0; q < g; q++ {
				w := complex64(root[(j*l1*(i0+q))%n])
				f[at+q], f[at+g+q] = real(w), imag(w)
				c[at+q], c[at+g+q] = real(w), -imag(w)
			}
			at += 2 * g
		}
		i0 += g
	}
	return pairs32(f), pairs32(c)
}

// pairs32 packs consecutive float32s two by two into complex64s.
func pairs32(f []float32) []complex64 {
	out := make([]complex64, len(f)/2)
	for i := range out {
		out[i] = complex(f[2*i], f[2*i+1])
	}
	return out
}

// twGroups returns the sizes of the twiddle groups of a pass with ido points
// per block, in walk order: ido/4 groups of four, then a group of two if
// ido&2, then a group of one if ido&1.
func twGroups(ido int) []int {
	gs := make([]int, 0, ido/4+2)
	for range ido / 4 {
		gs = append(gs, 4)
	}
	if ido&2 != 0 {
		gs = append(gs, 2)
	}
	if ido&1 != 0 {
		gs = append(gs, 1)
	}
	return gs
}

// stockham32Kernel reports whether a NEON kernel runs a float32 pass of radix
// r with ido points per block and l1 blocks: radix 2, 3, 4, 5 or 8, for any
// ido >= 2 and, as the final pass (ido == 1), for l1 a multiple of four.
func stockham32Kernel(r, ido, l1 int) bool {
	switch r {
	case 2, 3, 4, 5, 8:
		return ido > 1 || l1%4 == 0
	}
	return false
}

type (
	sk32PassFn func(cc, ch, tw *complex64, ido, l1 int)
	sk32LastFn func(cc, ch *complex64, l1 int)
)

var (
	sk32Pass    = [9]sk32PassFn{2: sk32Pass2NEON, 3: sk32Pass3NEON, 4: sk32Pass4NEON, 5: sk32Pass5NEON, 8: sk32Pass8NEON}
	sk32PassInv = [9]sk32PassFn{2: sk32Pass2NEONInv, 3: sk32Pass3NEONInv, 4: sk32Pass4NEONInv, 5: sk32Pass5NEONInv, 8: sk32Pass8NEONInv}
	sk32Last    = [9]sk32LastFn{2: sk32Last2NEON, 3: sk32Last3NEON, 4: sk32Last4NEON, 5: sk32Last5NEON, 8: sk32Last8NEON}
	sk32LastInv = [9]sk32LastFn{2: sk32Last2NEONInv, 3: sk32Last3NEONInv, 4: sk32Last4NEONInv, 5: sk32Last5NEONInv, 8: sk32Last8NEONInv}
)

// StockhamPass32 runs one float32 Stockham pass of radix r on a NEON kernel
// and reports true, or reports false (and does nothing) when no kernel runs
// it (stockham32Kernel). cc holds r·ido·l1 inputs, ch receives as many
// outputs, and tw is StockhamTwiddles32's table for the direction (unused by
// the final pass, ido == 1). It panics when ido or l1 is below 1 or a slice
// is shorter than the pass reads or writes: the kernels trust these lengths.
func StockhamPass32(r, ido, l1 int, cc, ch, tw []complex64, inverse bool) bool {
	if ido < 1 || l1 < 1 {
		panic("kernels: StockhamPass32: need ido and l1 >= 1")
	}
	if !UseStockham32 || !stockham32Kernel(r, ido, l1) {
		return false
	}
	n := r * ido * l1
	_, _ = cc[n-1], ch[n-1] // the kernels trust these lengths
	if ido == 1 {
		last := sk32Last[r]
		if inverse {
			last = sk32LastInv[r]
		}
		last(&cc[0], &ch[0], l1)
		return true
	}
	_ = tw[(r-1)*ido-1]
	pass := sk32Pass[r]
	if inverse {
		pass = sk32PassInv[r]
	}
	pass(&cc[0], &ch[0], &tw[0], ido, l1)
	return true
}

//go:noescape
func sk32Pass2NEON(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass2NEONInv(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass3NEON(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass3NEONInv(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass4NEON(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass4NEONInv(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass5NEON(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass5NEONInv(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass8NEON(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Pass8NEONInv(cc, ch, tw *complex64, ido, l1 int)

//go:noescape
func sk32Last2NEON(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last2NEONInv(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last3NEON(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last3NEONInv(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last4NEON(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last4NEONInv(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last5NEON(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last5NEONInv(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last8NEON(cc, ch *complex64, l1 int)

//go:noescape
func sk32Last8NEONInv(cc, ch *complex64, l1 int)
