package kernels

import "math"

// Stockham pass kernels for the fft package's stockham.go, generated by
// go-asmgen into butterfly_amd64.s (asmgen/amd64/gen.go, genStockhamAVX2). They
// run a whole pass of radix 2, 3, 4, 5, 8 or 16 two points per YMM register, and are
// bit-identical to stockham.go's scalar passes built for GOAMD64=v1: the same
// operations in the same order, separately rounded (no FMA), the rotations as
// exact lane swaps and sign flips, and the untwiddled i = 0 point restored by a
// blend rather than multiplied by one. TestStockhamPassMatchesScalar asserts it.

// UseStockhamAVX2 and UseStockhamAVX512 report whether StockhamPass may take
// the AVX2 and the AVX-512 kernels. They are variables so the tests can run
// every narrower path on a machine that has the wider one.
var (
	UseStockhamAVX2   = useAVX2
	UseStockhamAVX512 = supportsAVX512F()
)

// supportsAVX512F is the go-asmgen AVX-512 foundation probe (cpu_amd64.s): the
// CPU bit and the OS saving opmask and ZMM state.
func supportsAVX512F() bool

// IntelCPU reports whether CPUID names the vendor GenuineIntel. It only tunes
// the fft package's radix rule (route_amd64.go), which was measured to differ
// between Intel and AMD; no result depends on it. A hypervisor reporting its
// own vendor string reads as false, which keeps the default rule.
var IntelCPU = isGenuineIntel()

// isGenuineIntel is the go-asmgen CPUID leaf-0 vendor probe (cpu_amd64.s).
func isGenuineIntel() bool

// skConst512 is skConst with 64-byte rows, for the AVX-512 kernels. Its row 8,
// [-0, 0] repeated, is the real-lane sign flip that replaces VADDSUBPD, which
// has no 512-bit form.
type skConst512 [skConstRows][8]float64

var sk512Fwd, sk512Inv = newSKConst512(false), newSKConst512(true)

func newSKConst512(inverse bool) *skConst512 {
	var t skConst512
	narrow := newSKConst(inverse)
	for r := range narrow {
		for i := range t[r] {
			t[r][i] = narrow[r][i%4]
		}
	}
	return &t
}

// skConst holds the kernels' constants, one 32-byte row each (the offsets are
// the k* constants in gen.go): row 0 is the ±i rotation sign mask, which is
// what makes a table forward or inverse, and so are rows 13..16, the radix-16
// rows [−ss, ss, −ss, ss] with ss = s·sin θ (s = −1 forward, +1 inverse).
type skConst [skConstRows][4]float64

const skConstRows = 17

var skFwd, skInv = newSKConst(false), newSKConst(true)

func newSKConst(inverse bool) *skConst {
	neg := math.Copysign(0, -1)
	sign := [4]float64{0, neg, 0, neg} // rotS forward: (re,im) -> (im, -re)
	if inverse {
		sign = [4]float64{neg, 0, neg, 0} // inverse: (re,im) -> (-im, re)
	}
	row := func(v float64) [4]float64 { return [4]float64{v, v, v, v} }
	s := -1.0
	if inverse {
		s = 1
	}
	// ss rows: swap(a)·[−ss, ss] = (−ss·im, ss·re), radix16Rot's products.
	ss := func(v float64) [4]float64 { return [4]float64{-s * v, s * v, -s * v, s * v} }
	const (
		c1 = 0.92387953251128675612818318939678828682241662586364 // cos(π/8)
		s1 = 0.38268343236508977172845998403039886676134456248563 // sin(π/8)
		h  = 0.707106781186547524400844362104849                  // √2/2
	)
	return &skConst{
		sign,
		row(0.5),
		row(0.8660254037844386467637231707529361834714026269051903140279), // sin(2π/3)
		row(0.30901699437494742410229341718281905886015458990288),         // cos(2π/5)
		row(-0.80901699437494742410229341718281905886015458990289),        // cos(4π/5)
		row(0.95105651629515357211643933337938214340569863412575),         // sin(2π/5)
		row(0.58778525229247312916870595463907276859765243764314),         // sin(4π/5)
		row(h), // √2/2
		{neg, 0, neg, 0},
		row(c1),  // e = 1
		row(s1),  // e = 3
		row(-h),  // e = 6
		row(-c1), // e = 9
		ss(s1),   // e = 1
		ss(h),    // e = 2, 6
		ss(c1),   // e = 3
		ss(-s1),  // e = 9
	}
}

// stockhamSIMD reports whether a pass kernel exists for radix r.
func stockhamSIMD(r int) bool {
	switch r {
	case 2, 3, 4, 5, 8, 16:
		return true
	}
	return false
}

// StockhamTwiddles builds, for a pass of radix r with l1 earlier points and
// ido remaining ones, the twiddle table the kernels read, in forward and
// conjugate form: root is the size-n root table (root[k] = exp(-2πi·k/n)) and
// twiddle j of point i is root[(j·l1·i) mod n], i = 0..ido-1, j = 1..r-1. It
// returns nils when no kernel will run that pass.
//
// The table is laid out group by group, in the order every kernel walks the
// points (twGroups): groups of four, then one of two and one of one for ido
// mod 4. A group of g points starting at i0 stores twiddle 1 of points i0 ..
// i0+g-1, then twiddle 2 of the same points, and so on. A pass so reads its
// twiddles as one sequential stream. Laid out as r-1 runs of ido entries, a
// radix-8 pass read seven streams beside its eight inputs and eight outputs;
// grouped, radix-8 transforms ran 1.22–1.53× faster on Zen 3 from 2048 points
// on, radix-4 ones up to 1.21×, and 1.02–1.07× on Cascade Lake (2026-10-04,
// see BENCHMARKS.md).
func StockhamTwiddles(r, ido, l1 int, root []complex128) (fwd, conj []complex128) {
	if !stockhamSIMD(r) || ido < 2 {
		return nil, nil
	}
	if r == 16 {
		return radix16Twiddles(ido, l1, root)
	}
	n := len(root)
	fwd = make([]complex128, (r-1)*ido)
	conj = make([]complex128, (r-1)*ido)
	at, i0 := 0, 0
	for _, g := range twGroups(ido) {
		for j := 1; j < r; j++ {
			for i := i0; i < i0+g; i++ {
				w := root[(j*l1*i)%n]
				fwd[at] = w
				conj[at] = complex(real(w), -imag(w))
				at++
			}
		}
		i0 += g
	}
	return fwd, conj
}

// twGroups returns the sizes of the twiddle groups of a pass with ido points
// per block, in walk order: ido/4 groups of four, then a group of two if
// ido&2, then a group of one if ido&1. The AVX-512 kernels run a group of
// four per ZMM register and the AVX2 kernels as two YMM pairs; both finish
// with the same 256- and 128-bit steps.
func twGroups(ido int) []int {
	gs := make([]int, 0, ido/4+2)
	for range ido / 4 {
		gs = append(gs, 4)
	}
	if ido&2 != 0 {
		gs = append(gs, 2)
	}
	if ido&1 != 0 {
		gs = append(gs, 1)
	}
	return gs
}

// stockhamWidth picks the widest kernel family that can run a pass of radix r
// with ido points per block: 512 bits needs AVX-512 allowed for the transform
// (wide512, see StockhamPass), a radix with a 512-bit kernel (2, 4 or 8), and
// either the final pass (ido == 1, vectorized across blocks) or ido >= 4 (four
// points per register, the first four blended); 256 bits needs AVX2 and a
// radix with a kernel; 0 means the Go pass. It is a pure function so every
// branch is tested on any machine (TestStockhamWidth).
func stockhamWidth(r, ido int, avx2, wide512 bool) int {
	switch {
	case wide512 && (r == 2 || r == 4 || r == 8) && (ido == 1 || ido >= 4):
		return 512
	case avx2 && stockhamSIMD(r):
		return 256
	}
	return 0
}

type (
	skPassFn func(cc, ch, tw *complex128, k *float64, ido, l1 int)
	skLastFn func(cc, ch *complex128, k *float64, l1 int)
)

// The kernels by radix, per width.
var (
	skPass256 = [17]skPassFn{2: skPass2AVX2, 3: skPass3AVX2, 4: skPass4AVX2, 5: skPass5AVX2, 8: skPass8AVX2, 16: skPass16AVX2}
	skLast256 = [17]skLastFn{2: skLast2AVX2, 3: skLast3AVX2, 4: skLast4AVX2, 5: skLast5AVX2, 8: skLast8AVX2, 16: skLast16AVX2}
	skPass512 = [17]skPassFn{2: skPass2AVX512, 4: skPass4AVX512, 8: skPass8AVX512}
	skLast512 = [17]skLastFn{2: skLast2AVX512, 4: skLast4AVX512, 8: skLast8AVX512}
)

// stockhamKernels returns, for a width stockhamWidth chose (256 or 512), the
// constants table for the direction and the radix-r pass and final-pass
// kernels. It only selects, so it is tested for both widths on any machine
// (TestStockhamKernels), whichever one the machine can run.
func stockhamKernels(r, w int, inverse bool) (k *float64, pass skPassFn, last skLastFn) {
	if w == 512 {
		k = &sk512Fwd[0][0]
		if inverse {
			k = &sk512Inv[0][0]
		}
		return k, skPass512[r], skLast512[r]
	}
	k = &skFwd[0][0]
	if inverse {
		k = &skInv[0][0]
	}
	return k, skPass256[r], skLast256[r]
}

// StockhamPass runs one Stockham pass of radix r on the widest SIMD kernel
// that can run it and reports true, or reports false (and does nothing) when
// none can: no AVX2, or a radix without a kernel. cc holds r·ido·l1 inputs, ch
// receives as many outputs, and tw is the pass's twiddle table extended to i =
// 0 ((r-1) blocks of ido entries; unused by the final pass, ido == 1).
//
// wide allows the AVX-512 kernels. The caller sets it for a transform whose
// length is a power of two and for nothing else: on Cascade Lake, AVX-512 sped
// powers of two up 1.16–1.49× (256–4096) but left composites at 0.88–1.04×,
// whether every pass or only the radix-2/4/8 passes went to 512 bits (the
// latter was worse, 0.83–0.94×); a transform that mixes widths, or runs
// radix-3/5/7 passes at 512 bits, pays for the core's 512-bit frequency
// license without enough work to amortize it. (2026-10-01)
func StockhamPass(r, ido, l1 int, cc, ch, tw []complex128, inverse, wide bool) bool {
	w := stockhamWidth(r, ido, UseStockhamAVX2, UseStockhamAVX512 && wide)
	if w == 0 {
		return false
	}
	n := r * ido * l1
	_, _ = cc[n-1], ch[n-1] // the kernels trust these lengths
	k, pass, last := stockhamKernels(r, w, inverse)
	if ido == 1 {
		last(&cc[0], &ch[0], k, l1)
		return true
	}
	_ = tw[skTwLen(r, ido)-1]
	pass(&cc[0], &ch[0], &tw[0], k, ido, l1)
	return true
}

//go:noescape
func skPass2AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skPass3AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skPass4AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skPass5AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skPass8AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast2AVX2(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skLast3AVX2(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skLast4AVX2(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skLast5AVX2(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skLast8AVX2(cc, ch *complex128, k *float64, l1 int)

// UseUntangleAVX2 reports whether Untangle takes the AVX2 kernel; a variable so
// the tests can compare it with the scalar loop on an AVX2 machine.
var UseUntangleAVX2 = useAVX2

// Untangle runs the real-FFT untangle for bins k = 1 .. 2·⌊half/2⌋ (half =
// (m-1)/2) on the AVX2 kernel and returns the last bin it produced, or 0 when
// it did nothing; the caller finishes the remaining bins, and the DC, Nyquist
// and middle bins, in Go. dst has m+1 entries, z and tw at least m.
func Untangle(dst, z, tw []complex128, m int) int {
	pairs := (m - 1) / 2 / 2
	if !UseUntangleAVX2 || pairs == 0 {
		return 0
	}
	_, _, _ = dst[m], z[m-1], tw[2*pairs] // the kernel trusts these lengths
	untangleAVX2(&dst[0], &z[0], &tw[0], &skFwd[0][0], m, pairs)
	return 2 * pairs
}

//go:noescape
func untangleAVX2(dst, z, tw *complex128, k *float64, m, pairs int)

// Retangle runs the real-FFT inverse untangle for k = 1 .. 2·⌊half/2⌋ (half =
// (m-1)/2) on the AVX2 kernel, writing z from the complete half spectrum x
// scaled by h = 0.5·scale, and returns the last k it produced, or 0 when it did
// nothing (UseUntangleAVX2 gates it too). z and tw hold at least m entries, x m+1.
func Retangle(z, x, tw []complex128, m int, h float64) int {
	pairs := (m - 1) / 2 / 2
	if !UseUntangleAVX2 || pairs == 0 {
		return 0
	}
	_, _, _ = z[m-1], x[m], tw[2*pairs]
	hv := [4]float64{h, h, h, h}
	retangleAVX2(&z[0], &x[0], &tw[0], &skFwd[0][0], &hv, m, pairs)
	return 2 * pairs
}

//go:noescape
func retangleAVX2(z, x, tw *complex128, k *float64, h *[4]float64, m, pairs int)

//go:noescape
func skPass2AVX512(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast2AVX512(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skPass4AVX512(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast4AVX512(cc, ch *complex128, k *float64, l1 int)

//go:noescape
func skPass8AVX512(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast8AVX512(cc, ch *complex128, k *float64, l1 int)

// UseStockhamBatchAVX2 reports whether StockhamBatchPass takes the AVX2
// kernels; a variable so the tests can compare them with the Go pass.
var UseStockhamBatchAVX2 = useAVX2

// StockhamBatchKernels reports whether StockhamBatchPass has kernels on this
// machine (AVX2), which is when the fft package runs a non-contiguous axis as
// batched passes instead of gathering its lines.
func StockhamBatchKernels() bool { return useAVX2 }

// skBatch256 holds the batched pass kernels by radix (genStockhamBatchAVX2).
var skBatch256 = [9]skBatchFn{2: skBatch2AVX2, 3: skBatch3AVX2, 4: skBatch4AVX2, 5: skBatch5AVX2, 8: skBatch8AVX2}

type skBatchFn func(cc, ch, tw *complex128, k *float64, ido, l1, pairs, odd, jin, jout, adjin, adjout int)

// StockhamBatchPass runs one Stockham pass of radix r over a batch of w
// transforms laid out side by side, and reports true, or reports false (and
// does nothing) when no kernel can: no AVX2, or a radix without a kernel.
// Point p of the batch is the w values cc[p·sIn : p·sIn+w] on input and
// ch[p·sOut : p·sOut+w] on output (sIn, sOut >= w), so a pass reads or writes
// a strip of an N-D array in place. tw is StockhamBatchTwiddles' table for the
// direction (unused when ido == 1). The arithmetic is the scalar pass's,
// operation for operation, on every value of the batch.
func StockhamBatchPass(r, ido, l1 int, cc, ch, tw []complex128, w, sIn, sOut int, inverse bool) bool {
	if w < 1 || sIn < w || sOut < w || ido < 1 || l1 < 1 {
		// The kernels walk p·sIn+j for j < w; a stride below w, or an empty
		// batch, is a layout the length check below cannot vouch for.
		panic("kernels: StockhamBatchPass: need w >= 1, sIn and sOut >= w, ido and l1 >= 1")
	}
	if !UseStockhamBatchAVX2 || !stockhamSIMD(r) || r == 16 {
		return false
	}
	n := r * ido * l1
	_, _ = cc[(n-1)*sIn+w-1], ch[(n-1)*sOut+w-1] // the kernels trust these lengths
	t := &skFwd[0][0]
	if inverse {
		t = &skInv[0][0]
	}
	tp := (*complex128)(nil)
	if ido > 1 {
		_ = tw[(ido-1)*(r-1)-1]
		tp = &tw[0]
	}
	skBatch256[r](&cc[0], &ch[0], tp, t, ido, l1, w/2, w&1, 16*ido*sIn, 16*l1*ido*sOut, 16*(sIn-w), 16*(sOut-w))
	return true
}

//go:noescape
func skBatch2AVX2(cc, ch, tw *complex128, k *float64, ido, l1, pairs, odd, jin, jout, adjin, adjout int)

//go:noescape
func skBatch3AVX2(cc, ch, tw *complex128, k *float64, ido, l1, pairs, odd, jin, jout, adjin, adjout int)

//go:noescape
func skBatch4AVX2(cc, ch, tw *complex128, k *float64, ido, l1, pairs, odd, jin, jout, adjin, adjout int)

//go:noescape
func skBatch5AVX2(cc, ch, tw *complex128, k *float64, ido, l1, pairs, odd, jin, jout, adjin, adjout int)

//go:noescape
func skBatch8AVX2(cc, ch, tw *complex128, k *float64, ido, l1, pairs, odd, jin, jout, adjin, adjout int)

//go:noescape
func skPass16AVX2(cc, ch, tw *complex128, k *float64, ido, l1 int)

//go:noescape
func skLast16AVX2(cc, ch *complex128, k *float64, l1 int)

// skTwLen is the length of StockhamTwiddles' table for a pass with ido >= 2.
func skTwLen(r, ido int) int {
	if r == 16 {
		return 2 * (r - 1) * ido
	}
	return (r - 1) * ido
}

// radix16Twiddles is StockhamTwiddles for radix 16: the same groups, but each
// twiddle stored as its halves pre-duplicated, so the kernel multiplies by
// them straight from memory. A group of g points stores, for j = 1..15, the g
// pairs (wr, wr), then the g pairs (wi, wi), each pair one complex128. It
// doubles the table, which Round 17 measured to cost the large transforms;
// radix 16 only runs up to 2048 points, and there it made the twiddled pass
// 7% faster on Zen 3 (2026-10-05).
func radix16Twiddles(ido, l1 int, root []complex128) (fwd, conj []complex128) {
	n := len(root)
	fwd = make([]complex128, 2*15*ido)
	conj = make([]complex128, len(fwd))
	at, i0 := 0, 0
	for _, g := range twGroups(ido) {
		for j := 1; j < 16; j++ {
			for i := i0; i < i0+g; i++ {
				w := root[(j*l1*i)%n]
				fwd[at] = complex(real(w), real(w))
				fwd[at+g] = complex(imag(w), imag(w))
				conj[at] = complex(real(w), real(w))
				conj[at+g] = complex(-imag(w), -imag(w))
				at++
			}
			at += g
		}
		i0 += g
	}
	return fwd, conj
}
