package kernels

import "math"

// Single-precision (complex64) Stockham pass kernels for the fft package's
// stockham32_passes.go, generated by go-asmgen into stockham32_amd64.s
// (asmgen/amd64/gen.go, genF32StockhamAVX2 and genF32StockhamLastAVX2). They
// run a whole pass of radix 2, 3, 4, 5 or 8 four points per YMM register and
// are bit-identical to the Go passes built for GOAMD64=v1: the same
// operations in the same order, separately rounded (no FMA), the rotations as
// exact lane swaps and sign flips, the untwiddled i = 0 point restored by a
// blend. TestStockham32PassMatchesScalar asserts it.

// UseStockham32 reports whether StockhamPass32 may take the AVX2 kernels; a
// variable so the tests can compare them with the Go passes.
var UseStockham32 = useAVX2

// skConst32 is skConst in float32: one 32-byte row per constant, at the same
// offsets (the k* constants of gen.go), each constant rounded once to float32
// from its exact value, as the Go passes' untyped constants are. Row 0 is the
// ±i rotation sign mask, which makes a table forward or inverse.
type skConst32 [8][8]float32

var sk32Fwd, sk32Inv = newSKConst32(false), newSKConst32(true)

func newSKConst32(inverse bool) *skConst32 {
	neg := float32(math.Copysign(0, -1))
	var sign [8]float32 // rotS forward: (re,im) -> (im, -re)
	for i := range sign {
		if i%2 == 1 != inverse { // inverse: (re,im) -> (-im, re)
			sign[i] = neg
		}
	}
	row := func(v float32) [8]float32 { return [8]float32{v, v, v, v, v, v, v, v} }
	return &skConst32{
		sign,
		row(0.5),
		row(0.8660254037844386467637231707529361834714026269051903140279), // sin(2π/3)
		row(0.30901699437494742410229341718281905886015458990288),         // cos(2π/5)
		row(-0.80901699437494742410229341718281905886015458990289),        // cos(4π/5)
		row(0.95105651629515357211643933337938214340569863412575),         // sin(2π/5)
		row(0.58778525229247312916870595463907276859765243764314),         // sin(4π/5)
		row(0.707106781186547524400844362104849),                          // √2/2
	}
}

// stockham32Kernel reports whether a kernel runs a pass of radix r with ido
// points per block and l1 blocks: radix 2, 3, 4, 5 and 8, any ido and l1.
func stockham32Kernel(r, ido, l1 int) bool {
	switch r {
	case 2, 3, 4, 5, 8:
		return true
	}
	return false
}

// StockhamTwiddles32 builds, for a float32 pass of radix r with l1 earlier
// points and ido remaining ones, the twiddle table the kernels read, in
// forward and conjugate form, each entry root[(j·l1·i) mod n] rounded once to
// complex64 (i = 0..ido-1, j = 1..r-1), or returns nils when no kernel runs
// the pass. The layout is StockhamTwiddles' (twGroups): groups of four points,
// one register each, then a group of two and one of one for ido mod 4, each
// group storing its r-1 twiddle runs back to back.
func StockhamTwiddles32(r, ido, l1 int, root []complex128) (fwd, conj []complex64) {
	if ido < 2 || !stockham32Kernel(r, ido, l1) {
		return nil, nil
	}
	n := len(root)
	fwd = make([]complex64, (r-1)*ido)
	conj = make([]complex64, len(fwd))
	at, i0 := 0, 0
	for _, g := range twGroups(ido) {
		for j := 1; j < r; j++ {
			for i := i0; i < i0+g; i++ {
				w := root[(j*l1*i)%n]
				fwd[at] = complex64(w)
				conj[at] = complex64(complex(real(w), -imag(w)))
				at++
			}
		}
		i0 += g
	}
	return fwd, conj
}

type (
	sk32PassFn func(cc, ch, tw *complex64, k *float32, ido, l1 int)
	sk32LastFn func(cc, ch *complex64, k *float32, l1 int)
)

var (
	sk32Pass = [9]sk32PassFn{2: sk32Pass2AVX2, 3: sk32Pass3AVX2, 4: sk32Pass4AVX2, 5: sk32Pass5AVX2, 8: sk32Pass8AVX2}
	sk32Last = [9]sk32LastFn{2: sk32Last2AVX2, 3: sk32Last3AVX2, 4: sk32Last4AVX2, 5: sk32Last5AVX2, 8: sk32Last8AVX2}
)

// StockhamPass32 runs one float32 Stockham pass of radix r on an AVX2 kernel
// and reports true, or reports false (and does nothing) when none can: no
// AVX2, or a radix without a kernel. cc holds r·ido·l1 inputs, ch receives as
// many outputs, and tw is StockhamTwiddles32's table for the direction
// (unused by the final pass, ido == 1). It panics when ido or l1 is below 1
// or a slice is shorter than the pass reads or writes: the kernels trust
// these lengths.
func StockhamPass32(r, ido, l1 int, cc, ch, tw []complex64, inverse bool) bool {
	if ido < 1 || l1 < 1 {
		panic("kernels: StockhamPass32: need ido and l1 >= 1")
	}
	if !UseStockham32 || !stockham32Kernel(r, ido, l1) {
		return false
	}
	n := r * ido * l1
	_, _ = cc[n-1], ch[n-1] // the kernels trust these lengths
	k := &sk32Fwd[0][0]
	if inverse {
		k = &sk32Inv[0][0]
	}
	if ido == 1 {
		sk32Last[r](&cc[0], &ch[0], k, l1)
		return true
	}
	_ = tw[(r-1)*ido-1]
	sk32Pass[r](&cc[0], &ch[0], &tw[0], k, ido, l1)
	return true
}

//go:noescape
func sk32Pass2AVX2(cc, ch, tw *complex64, k *float32, ido, l1 int)

//go:noescape
func sk32Pass3AVX2(cc, ch, tw *complex64, k *float32, ido, l1 int)

//go:noescape
func sk32Pass4AVX2(cc, ch, tw *complex64, k *float32, ido, l1 int)

//go:noescape
func sk32Pass5AVX2(cc, ch, tw *complex64, k *float32, ido, l1 int)

//go:noescape
func sk32Pass8AVX2(cc, ch, tw *complex64, k *float32, ido, l1 int)

//go:noescape
func sk32Last2AVX2(cc, ch *complex64, k *float32, l1 int)

//go:noescape
func sk32Last3AVX2(cc, ch *complex64, k *float32, l1 int)

//go:noescape
func sk32Last4AVX2(cc, ch *complex64, k *float32, l1 int)

//go:noescape
func sk32Last5AVX2(cc, ch *complex64, k *float32, l1 int)

//go:noescape
func sk32Last8AVX2(cc, ch *complex64, k *float32, l1 int)
