//go:build amd64 || arm64

package kernels

// The float32 real-FFT untangle and its inverse (Round 25): the fft package's
// f32Untangle and f32Retangle loops on a SIMD kernel, four bins per
// iteration, generated by go-asmgen (genF32RealFile in asmgen/amd64/gen.go
// and asmgen/arm64/gen.go). On amd64 the AVX2 kernels round every operation
// separately, as gc compiles the Go loops for GOAMD64=v1; on arm64 the NEON
// kernels fuse exactly the products gc fuses into FMADDS/FMSUBS/FNMSUBS. Both
// are bit-identical to the Go loops (TestUntangle32MatchesScalar).

// f32rQuads is how many groups of four bins a kernel produces for a
// half-length m: the bins k = 1 .. (m-1)/2 that pair with m-k, in fours. It is
// 0 or negative when m is too small (or negative) for one group.
func f32rQuads(m int) int { return (m - 1) / 2 / 4 }

// Untangle32 runs the float32 real-FFT untangle for bins k = 1 .. 4·quads
// (and their mirrors m-k), quads = ⌊(m-1)/2/4⌋, on the SIMD kernel and
// returns the last bin it produced, or 0 when it did nothing; the caller
// finishes the remaining bins, and the DC, Nyquist and middle bins, in Go.
// dst holds at least m+1 entries, z m and tw 4·quads+1: the bound checks
// below panic before the kernel runs when one is shorter.
func Untangle32(dst, z, tw []complex64, m int) int {
	quads := f32rQuads(m)
	if !UseUntangle32 || quads <= 0 {
		return 0
	}
	_, _, _ = dst[m], z[m-1], tw[4*quads] // the kernel trusts these lengths
	f32rUntangle(&dst[0], &z[0], &tw[0], m, quads)
	return 4 * quads
}

// Retangle32 runs the inverse untangle for k = 1 .. 4·quads on the SIMD
// kernel, writing z (and its mirrors z[m-k]) from the complete half spectrum
// x scaled by h, and returns the last k it produced, or 0 when it did
// nothing. z holds at least m entries, x m+1 and tw 4·quads+1.
func Retangle32(z, x, tw []complex64, m int, h float32) int {
	quads := f32rQuads(m)
	if !UseUntangle32 || quads <= 0 {
		return 0
	}
	_, _, _ = z[m-1], x[m], tw[4*quads]
	f32rRetangle(&z[0], &x[0], &tw[0], h, m, quads)
	return 4 * quads
}
