package kernels

// The float64 real-FFT untangle and its inverse on NEON (Round 27): the fft
// package's rfftUntangle and irfftRetangle loops, two bins per iteration,
// generated by go-asmgen (genArmrealUntangleFile in asmgen/arm64/gen.go into
// untangle_arm64.s). They fuse exactly the products gc fuses into
// FMADDD/FMSUBD/FNMSUBD, so outside -race they are bit-identical to the Go
// loops (TestUntangleMatchesScalarNEON).

// UseUntangleNEON reports whether Untangle and Retangle take the NEON
// kernels: always, NEON being part of the arm64 baseline; a variable so the
// tests can compare them with the Go loops.
var UseUntangleNEON = true

// armrealPairs is how many pairs of bins a kernel produces for a half-length
// m: the bins k = 1 .. (m-1)/2 that pair with m-k, in twos. It is 0 or
// negative when m is too small (or negative) for one pair.
func armrealPairs(m int) int { return (m - 1) / 2 / 2 }

// Untangle runs the real-FFT untangle for bins k = 1 .. 2·pairs (and their
// mirrors m-k), pairs = ⌊(m-1)/2/2⌋, on the NEON kernel and returns the last
// bin it produced, or 0 when it did nothing; the caller finishes the
// remaining bins, and the DC, Nyquist and middle bins, in Go. dst holds at
// least m+1 entries, z m and tw 2·pairs+1: the bound checks below panic
// before the kernel runs when one is shorter.
func Untangle(dst, z, tw []complex128, m int) int {
	pairs := armrealPairs(m)
	if !UseUntangleNEON || pairs <= 0 {
		return 0
	}
	_, _, _ = dst[m], z[m-1], tw[2*pairs] // the kernel trusts these lengths
	armrealUntangleNEON(&dst[0], &z[0], &tw[0], m, pairs)
	return 2 * pairs
}

// Retangle runs the inverse untangle for k = 1 .. 2·pairs on the NEON kernel,
// writing z (and its mirrors z[m-k]) from the complete half spectrum x scaled
// by h = 0.5·scale, and returns the last k it produced, or 0 when it did
// nothing. z holds at least m entries, x m+1 and tw 2·pairs+1.
func Retangle(z, x, tw []complex128, m int, h float64) int {
	pairs := armrealPairs(m)
	if !UseUntangleNEON || pairs <= 0 {
		return 0
	}
	_, _, _ = z[m-1], x[m], tw[2*pairs]
	armrealRetangleNEON(&z[0], &x[0], &tw[0], &h, m, pairs)
	return 2 * pairs
}

//go:noescape
func armrealUntangleNEON(dst, z, tw *complex128, m, pairs int)

//go:noescape
func armrealRetangleNEON(z, x, tw *complex128, h *float64, m, pairs int)
